-- MySQL Script generated by MySQL Workbench
-- Sat Nov 30 23:06:04 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Moderators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Moderators` (
  `moderator_id` INT(32) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `surname` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`moderator_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Groups` (
  `group_id` INT(32) NOT NULL,
  `moderator_id` INT(32) NULL,
  `group_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`group_id`),
  INDEX `moderator_id_idx` (`moderator_id` ASC) VISIBLE,
  CONSTRAINT `moderator_id`
    FOREIGN KEY (`moderator_id`)
    REFERENCES `mydb`.`Moderators` (`moderator_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Students` (
  `student_id` INT(32) NULL,
  `name` VARCHAR(255) NOT NULL,
  `surname` VARCHAR(255) NOT NULL,
  `group_id` INT(32) NULL,
  PRIMARY KEY (`student_id`),
  INDEX `group_id_idx` (`group_id` ASC) VISIBLE,
  CONSTRAINT `group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `mydb`.`Groups` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Courses` (
  `course_id` INT(32) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` LONGTEXT NOT NULL,
  PRIMARY KEY (`course_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tests` (
  `test_id` INT(32) NULL,
  `course_id` INT(32) NOT NULL,
  `topic_title` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`test_id`),
  INDEX `course_id_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `course_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`Courses` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Questions` (
  `question_id` INT(32) NULL,
  `test_id` INT(32) NOT NULL,
  `content` MEDIUMTEXT NOT NULL,
  `question_type` VARCHAR(45) NOT NULL COMMENT 'only \'TRUE_FALSE\', \'TEST\', \'OPEN\', \'CONNECT\' are valid values',
  PRIMARY KEY (`question_id`),
  INDEX `test_id_idx` (`test_id` ASC) VISIBLE,
  CONSTRAINT `test_id`
    FOREIGN KEY (`test_id`)
    REFERENCES `mydb`.`Tests` (`test_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Answers` (
  `answer_id` INT(32) NULL,
  `question_id` INT(32) NOT NULL,
  `anwer_content` MEDIUMTEXT NOT NULL,
  `is_right` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`answer_id`),
  INDEX `question_id_idx` (`question_id` ASC) VISIBLE,
  CONSTRAINT `question_id`
    FOREIGN KEY (`question_id`)
    REFERENCES `mydb`.`Questions` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StudentTestAnswers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`StudentTestAnswers` (
  `result_id` INT(32) NULL,
  `student_id` INT(32) NOT NULL,
  `answer_id` INT(32) NOT NULL,
  `submited_time` TIMESTAMP(8) NOT NULL,
  PRIMARY KEY (`result_id`),
  INDEX `student_id_idx` (`student_id` ASC) VISIBLE,
  INDEX `answer_id_idx` (`answer_id` ASC) VISIBLE,
  CONSTRAINT `student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`Students` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `answer_id`
    FOREIGN KEY (`answer_id`)
    REFERENCES `mydb`.`Answers` (`answer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StudentsCourses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`StudentsCourses` (
  `student_id` INT(32) NOT NULL,
  `course_id` INT(32) NOT NULL,
  `completed_date` DATETIME NULL,
  INDEX `student_id_idx` (`student_id` ASC) VISIBLE,
  INDEX `course_id_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`Students` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `course_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`Courses` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StudentOpenQuestionAnswers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`StudentOpenQuestionAnswers` (
  `result_id` INT(32) NULL,
  `question_id` INT(32) NOT NULL,
  `student_id` INT(32) NOT NULL,
  `answer` MEDIUMTEXT NOT NULL,
  `submited_time` TIMESTAMP(8) NOT NULL,
  PRIMARY KEY (`result_id`),
  INDEX `student_id_idx` (`student_id` ASC) VISIBLE,
  INDEX `question_id_idx` (`question_id` ASC) VISIBLE,
  CONSTRAINT `student_id0`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`Students` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `question_id`
    FOREIGN KEY (`question_id`)
    REFERENCES `mydb`.`Questions` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ConnectQuestionsAnswers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ConnectQuestionsAnswers` (
  `connect_question_answer_id` INT(32) NOT NULL,
  `answer_id` INT(32) NOT NULL,
  `correct_pair_answer_id` INT(32) NOT NULL,
  PRIMARY KEY (`connect_question_answer_id`),
  UNIQUE INDEX `answer_id_UNIQUE` (`answer_id` ASC) VISIBLE,
  UNIQUE INDEX `correct_pair_answer_id_UNIQUE` (`correct_pair_answer_id` ASC) VISIBLE,
  CONSTRAINT `answer_id`
    FOREIGN KEY (`answer_id`)
    REFERENCES `mydb`.`Answers` (`answer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `correct_pair_answer_id`
    FOREIGN KEY (`correct_pair_answer_id`)
    REFERENCES `mydb`.`Answers` (`answer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StudentConnectQuestionsAnswers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`StudentConnectQuestionsAnswers` (
  `student_connect_questions_answer_id` INT(32) NOT NULL,
  `student_id` INT(32) NOT NULL,
  `answer_id` INT(32) NOT NULL,
  `pair_answer_id` INT(32) NOT NULL,
  `submited_time` TIMESTAMP(8) NOT NULL,
  PRIMARY KEY (`student_connect_questions_answer_id`),
  UNIQUE INDEX `pair_answer_id_UNIQUE` (`pair_answer_id` ASC) VISIBLE,
  UNIQUE INDEX `answer_id_UNIQUE` (`answer_id` ASC) VISIBLE,
  INDEX `student_id_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `answer_id`
    FOREIGN KEY (`answer_id`)
    REFERENCES `mydb`.`Answers` (`answer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pair_answer_id`
    FOREIGN KEY (`pair_answer_id`)
    REFERENCES `mydb`.`Answers` (`answer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`Students` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StudentsTests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`StudentsTests` (
  `students_test_id` INT(32) NOT NULL,
  `student_id` INT(32) NOT NULL,
  `test_id` INT(32) NOT NULL,
  `completed_date` DATETIME NULL,
  PRIMARY KEY (`students_test_id`),
  INDEX `student_id_idx` (`student_id` ASC) VISIBLE,
  INDEX `test_id_idx` (`test_id` ASC) VISIBLE,
  CONSTRAINT `student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`Students` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `test_id`
    FOREIGN KEY (`test_id`)
    REFERENCES `mydb`.`Tests` (`test_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb`;

DELIMITER $$
USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`StudentsCourses_AFTER_INSERT` AFTER INSERT ON `StudentsCourses` FOR EACH ROW
BEGIN
	INSERT INTO StudentsTests(student_id, test_id, completed) (SELECT OLD.student_id, test_id, false FROM Tests WHERE course_id = OLD.course_id);
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`StudentsCourses_AFTER_DELETE` AFTER DELETE ON `StudentsCourses` FOR EACH ROW
BEGIN
	DELETE FROM StudentsTests WHERE test_id IN (SELECT test_id FROM Tests AS t WHERE t.course_id = OLD.course_id);
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
